apiVersion: batch/v1
kind: Job
metadata:
  name: bullmq-producer
  namespace: bullmq-test
spec:
  template:
    spec:
      containers:
        - name: producer
          image: bullmq-worker:latest
          imagePullPolicy: Never
          command: ["node", "dist/producer.js"]
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
      restartPolicy: Never
